language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install --upgrade "git+https://github.com/fsepy/fsetools.git@dev"
  - pip install .
  - pip install codecov
  - pip install pytest-cov
script:
  - pytest --cov-report term --cov=sfeprapy/
after_success:
  - codecov
